### ISSUE TITLE
$CURV_EDITOR not defined 

### ISSUE THREAD

**Issue by Cdriko** [doug-moen/curv#26]
Hello
I discover curv with a lot of pleasure, in ubuntu 16.04, but I fail to launch it in livemode
I got

`$ curv -le`

```
-e specified but $CURV_EDITOR not defined
Use curv --help for help.

```

I tried to set the 
`CURV_EDITOR=gedit`

but the result is the same.
I've installed glslViewer, but not much better result.

any idea?

**Comment by doug-moen** [comment]
This should now be fixed. There were two bugs here.
 1. The CURV_EDITOR variable now has a default value, so you should no longer get this error
    message, or worry about setting it. Curv now defaults to using the "gedit" text editor.
 2. "curv -le" should fail with a "missing filename" error. Previously, the error message was wrong.
 That bug is now fixed.

To use curv, type `curv -le foo.curv`, where `foo.curv` is some file name. The file name must be specified, even if the file doesn't exist yet.
