### ISSUE TITLE
Export STL enhancement

### ISSUE THREAD

**Issue by gsohler** [doug-moen/curv#29]
When exporting to STL the normal vector is always created as 0 0 0
This might be a problem for viewers which change brightness of a face dependant on the angle its
viewed from
BTW: Can I find a function reference manual somewhere ?

**Comment by gsohler** [comment]
Hi Dough,

Sorry, i was not aware, that the normal vector is optional.
Its my own STL viewer, which relies on it :) 

This is why you could not find the mismatch.

You could save some bytes when exporting binary STL. In this case using normal vectors
does not cause additional space.

Thank you for the documentation link!

**Comment by gsohler** [comment]
Hi Dough,
Now the lollipop appears correctly in my viewer.
![capture-lollipop](https://user-images.githubusercontent.com/8711730/43076090-5f334b44-8e83-11e8-95d7-15c3a63d364d.PNG)

Thank you very much.

**Comment by gsohler** [comment]
Curv is sooo cool. Its so much better than OpenSCAD.
I think one year before I had the idea to express arbritray shapes by the "altitude above to the surface" but I failed.
Are there plans to create an OpenSCAD to curv syntax converter ?
Which are the challenges to offer a Windows curv version ?

**Comment by doug-moen** [comment]
@gsohler said: "Curv is sooo cool. Its so much better than OpenSCAD."
Thanks. Those were the 2 main design goals 😀

I'd like to create a Windows version, but I have little relevant experience and I don't have access to a Windows dev machine. Some of the C++ code probably won't work on Windows and will need to be rewritten. I'm getting there slowly: I recently eliminated 2 external dependencies that aren't Windows compatible. If I had another contributor with both Windows and C++ experience, it would go much faster.

The Curv project was originally called OpenSCAD2, but I dropped the goal of OpenSCAD compatibility a few years ago, because it was too much of a burden. The radically different internal representation of shapes makes OpenSCAD compatibility quite difficult. There are some OpenSCAD operations that I don't support. Even the OpenSCAD cylinder primitive is problematic, since `cylinder(d=1, h=1, $fn=6);` is how you create a hexagonal prism. A one way source code converter that works 80% of the time might be doable, but I bet there would be a lot of issues. I'd prefer that someone else write the converter as a separate project, so that I'm not on the hook to maintain it.

I think the big missing feature from the perspective of OpenSCAD users is the ability to import STL files. That's something I'm working towards right now. I'm actually implementing image file import first, as that is easier, and requires some of the same code changes that I'll need later.

I think the big missing feature from the perspective of Windows users is the fact that I don't have a "real" GUI. I recently got closer when I integrated the 3D viewing window code into the Curv executable. Now I'm just missing integrated editor and integrated console windows. Windows has this weird distinction between "console applications" and "windows applications" that doesn't exist in Linux or macOS. Curv right now would be a "console application" if it were ported to Windows, and it really needs to be a "windows application" in order to look and feel like a native application. To be more precise, I feel I need separate console and GUI executables with different names.

**Comment by gsohler** [comment]
Dough, not sure how much I can help you out, but I can give you some suggestions, if you are not yet aware of them.
There is a Windows development system called MSYS2 (msys2.org). When installed you get a unix like terminal in windows. It can create Binaries, which run in native windows and there are many prebuild libraries(use pacman)

Which were the 2 external dependancies you got working recently ?


.... I think, i did not yet see a replacement for "hull". but there are many similar ones ...

The only chance where I need importSTL to change existing STL's (change dimentions and/or cut/add stuff). Apart from that i dont see use for that.

One very nice Editor I know in Windows is Notepad++. It's developped under GPL, is very intuitive/clever and has great Syntax highlighting. And even in Windows, there are triggers when a File's date has changed.
Would like to see that :)

Cheers, Günther
